# Generated by Django 6.1 on 2026-08-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['customer_id'], name='customers_custome_b85ebb_idx'), models.Index(fields=['is_active', 'created_at'], name='customers_is_acti_a847c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MAGIC_LINK_CREATED', 'Magic Link Created'), ('MAGIC_LINK_USED', 'Magic Link Used'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('DEVICE_CREATED', 'Device Created'), ('DEVICE_REVOKED', 'Device Revoked'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_UPDATED', 'Request Updated'), ('IMAGE_UPLOADED', 'Image Uploaded'), ('LINK_REVOKED', 'Link Revoked'), ('ADMIN_ACTION', 'Admin Action'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['customer', 'created_at'], name='audit_logs_custome_3cd2f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_devices',
                'indexes': [models.Index(fields=['credential_hash'], name='customer_de_credent_7f77b7_idx'), models.Index(fields=['customer', 'is_active'], name='customer_de_custome_71e74c_idx'), models.Index(fields=['expires_at', 'revoked_at'], name='customer_de_expires_697e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('max_activations', models.PositiveSmallIntegerField(default=5)),
                ('successful_activations', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('EXHAUSTED', 'Exhausted')], default='ACTIVE', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='customers.customer')),
            ],
            options={
                'db_table': 'magic_links',
                'indexes': [models.Index(fields=['token_hash'], name='magic_links_token_h_8d6287_idx'), models.Index(fields=['status', 'expires_at'], name='magic_links_status_207ba2_idx'), models.Index(fields=['customer', 'status'], name='magic_links_custome_f97f9e_idx')],
            },
        ),
    ]
