# Generated by Django 6.1 on 2026-08-16 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True, verbose_name='شماره ردیف')),
                ('bill_number', models.CharField(max_length=50, unique=True, verbose_name='شماره قبض')),
                ('is_warranty', models.BooleanField(default=False, verbose_name='گارانتی دارد')),
                ('operation_type', models.CharField(max_length=100, verbose_name='نوع عملیات')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('product_type', models.CharField(max_length=50, verbose_name='نوع محصول')),
                ('acceptance_date', models.CharField(max_length=20, verbose_name='تاریخ پذیرش')),
                ('registration_code', models.CharField(max_length=50, verbose_name='کد ثبت')),
                ('issuer_name', models.CharField(max_length=200, verbose_name='نام صادر کننده قبض')),
                ('product_model', models.CharField(max_length=200, verbose_name='مدل محصول')),
                ('serial_number', models.CharField(max_length=100, verbose_name='شماره سریال محصول')),
                ('completion_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ اتمام یا تحویل')),
                ('address', models.TextField(verbose_name='نشانی')),
                ('has_warranty_card', models.BooleanField(default=False, verbose_name='شماره کارت گارانتی دارد')),
                ('warranty_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت گارانتی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('service_status', models.CharField(max_length=100, verbose_name='وضعیت سرویس')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('token_used', models.BooleanField(default=False, verbose_name='توکن استفاده شده')),
                ('token_used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده توکن')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('gas_stove', 'اجاق گاز'), ('hood', 'هود'), ('oven', 'فر'), ('package', 'پکیج'), ('other', 'سایر')], max_length=20, verbose_name='نوع محصول')),
                ('product_model', models.CharField(max_length=200, verbose_name='مدل محصول')),
                ('problem_description', models.TextField(verbose_name='شرح مشکل')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('contacted', 'تماس گرفته شد'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ادمین')),
                ('contact_called', models.BooleanField(default=False, verbose_name='تماس گرفته شد')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تماس')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'درخواست خدمات',
                'verbose_name_plural': 'درخواست\u200cهای خدمات',
                'ordering': ['-request_date'],
            },
        ),
    ]
