# Generated by Django 6.1 on 2026-08-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('appliance_type', models.CharField(choices=[('GAS_STOVE', 'اجاق گاز'), ('HOOD', 'هود'), ('OVEN', 'فر'), ('PACKAGE', 'پکیج'), ('COOLER', 'کولر'), ('REFRIGERATOR', 'یخچال'), ('FREEZER', 'فریزر'), ('WASHING_MACHINE', 'ماشین لباسشویی'), ('DISHWASHER', 'ماشین ظرفشویی'), ('MICROWAVE', 'مایکروفر'), ('OTHER', 'سایر')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'ثبت شده'), ('UNDER_REVIEW', 'در حال بررسی'), ('WAITING_COORDINATION', 'در انتظار هماهنگی'), ('TECHNICIAN_ASSIGNED', 'تعمیرکار تعیین شد'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تکمیل شد'), ('CANCELLED', 'لغو شد')], default='NEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customers.customer')),
            ],
            options={
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'request_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='requests/thumbnails/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('original_filename', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'service_request_images',
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['tracking_code'], name='service_req_trackin_79819d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'status'], name='service_req_custome_7d484f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='service_req_status_9bff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='service_req_created_bc6133_idx'),
        ),
        migrations.AddIndex(
            model_name='requeststatushistory',
            index=models.Index(fields=['request', 'changed_at'], name='request_sta_request_040e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestimage',
            index=models.Index(fields=['request', 'uploaded_at'], name='service_req_request_432ecb_idx'),
        ),
    ]
